### ISSUE TITLE
NJKWebViewProgress 库冲突

### ISSUE THREAD

**Issue by davidtan2008** [qunarcorp/imsdk-ios#15]
待集成的项目里有NJKWebViewProgress静态库
用pod 的方式集成QIMUIKit的话，会导致NJKWebViewProgress冲突。

**Comment by Lidalu** [comment]
QIMUIKit默认以Pod方式依赖了NJKWebViewProgress等开源三方库，如果你本地的其他静态库里也包含了这些三方库，这种情况有两种解决办法：

解决办法1： 可以在使用post_install在生成.xcworkspace项目时，移除pod形式依赖的NJKWebViewProgress三方库。这样QIMUIKit在运行时会自动指向你本地静态库中的NJKWebViewProgress库。
解决办法2： 使用lipo -info查看本地静态库，并拆解出来NJKWebViewProgress，再使用lipo -create重新生成静态库。

但这一切一切的前提是静态库中的NJKWebViewProgress完全没有更改过源码，并且能够保证最新版本，否则即使按照上面👆两种办法解决了，运行时也会出现方法找不到，而导致崩溃。（PS：一般正常人也不会把开源三方库打进自己的SDK静态库吧，如果更改了第三方源码，还打进了自己的静态库，也应该改一下类名，防止出现类名冲突）
