### ISSUE TITLE
扩展键盘问题

### ISSUE THREAD

**Issue by 1454879305** [qunarcorp/imsdk-ios#30]
输入框下方的扩展键盘能支持自定义吗？现在默认的好几个按钮都用不到

**Comment by Lidalu** [comment]
如果需要移除扩展键盘中的某个按钮，可以在启动QIMSDK之前调用
`[[QIMKit sharedInstance] removeExpandItemsForItemId:@"itemId"];`
这里的itemId定义在`QIMTextBarExpandView.h`头文件中
