### ISSUE TITLE
cocoaPods导入类库冲突

### ISSUE THREAD

**Issue by alienJion** [qunarcorp/imsdk-ios#32]
### 问题检查清单

感谢您向我们提出问题，在提交问题之前，请确认以下事宜：

- [x] 我已经阅读了组件文档:
 
     [《Startalk客户端配置导航》](https://im.qunar.com/new/#/platform/access_guide/manage_nav?id=manage_nav_mb)

     [《QIMSDK iOS接入文档》](https://github.com/qunarcorp/imsdk-ios/wiki/QIMSDK-iOS%E6%8E%A5%E5%85%A5%E6%96%87%E6%A1%A3)

     [《QIMSDK iOS接口文档说明》](https://github.com/qunarcorp/imsdk-ios/wiki/QIMSDK-iOS%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3%E8%AF%B4%E6%98%8E)

     [《QIMSDK Scheme跳转说明》](https://github.com/qunarcorp/imsdk-ios/wiki/QIMSDK-Scheme%E8%B7%B3%E8%BD%AC%E8%AF%B4%E6%98%8E)

     [《QIMSDK 文档说明》](https://github.com/qunarcorp/imsdk-ios/wiki/QIMSDK-%E6%96%87%E6%A1%A3%E8%AF%B4%E6%98%8E)

     [《QIMSDK Changelog》](https://github.com/qunarcorp/imsdk-ios/wiki/QIMSDKDemo-Changelog)
     
- [x] 我已经搜索了[当前问题](https://github.com/qunarcorp/imsdk-ios/issues?utf8=%E2%9C%93&q=is%3Aissue), 但是找不到相关解决方案。

### 问题描述
按照《QIMSDK iOS接入文档》接入成功后编译报错。

#### 问题现象
具体错误信息：
![屏幕快照 2019-03-19 下午2 07 52](https://user-images.githubusercontent.com/21168365/54584359-17e26f00-4a52-11e9-91ab-ccf3763617d0.png)

[描述具体问题表现]
项目中使用并导入了YYKit框架，作者项目中使用了YYModel，引起的类库冲突文件。
解决方案：
对项目中使用到的YYKit类库进行单独引入。

**Comment by Lidalu** [comment]
感谢反馈，YYKit相当于一个大集合，与YYModel，YYCache这些组件库本身会冲突。建议用到哪些组件引用哪些组件，没有必要集成整个YYKit。 具体原因详见[YYKit issue #82](https://github.com/ibireme/YYModel/issues/82)
