### ISSUE TITLE
聊天页面发送位置 显示有异常

### ISSUE THREAD

**Issue by dongyuekai** [qunarcorp/imsdk-ios#36]
聊天页面发送位置：
发送完成后缩略图显示出定位的位置，点击缩略图查看也不能找到定位的位置，显示定位在非洲：
![DD831E5A3C2E5C27B37AD9516F3C191F](https://user-images.githubusercontent.com/16332837/57568619-8a514900-741c-11e9-86b1-42589e83b8ee.jpg)
返回上一页在进来就正常了：
![FD085E5D1E69B2C795DC363C3D6C10FF](https://user-images.githubusercontent.com/16332837/57568626-b240ac80-741c-11e9-82df-9becdbefd5e2.jpg)

**Comment by Lidalu** [comment]
已Fix，更新最新版本sdk就行。
