### ISSUE TITLE
包体积大，瘦身问题

### ISSUE THREAD

**Issue by TYJ1990** [qunarcorp/imsdk-ios#41]
因为现在包体积过大，但项目中只用了基础功能，有没有办法不依赖多余的功能（类似音视频通话）

**Comment by Lidalu** [comment]
1. 远程Pod方式：
   你可以在podfile文件中添加post_install，对QIMGeneralModule组件进行移除。
2. 本地Pod方式：

   - 看一下QIMGeneralModule.podspec 文件，里面有各个小组件（音视频，日历，笔记本，日志，埋点等功能）
   - 在Podfile文件中选择性依赖QIMGeneralModule中的组件，例 pod 'QIMGeneralModule/WebRTC'
   - 如果QIMGeneralModule.podspec中的组件对你都没有用，可以直接在Podfile文件中删掉QIMGeneralModule依赖。

**Comment by TYJ1990** [comment]
我们项目只用到了基础功能，聊天。所以有些字体和图片音频文件都可以适当的删除一些，还有发送代码段的功能的qimSourceCode.bundle以及记事本功能的CKEditor5.bundle都可以删掉。
